Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -52,7 +52,51 @@ jobs:
         run: emulator -list-avds
         
       - name: Start emulator
-        run: emulator -avd "$EMULATOR_NAME" -no-audio -no-window -qemu -use-system-libs -"accel on" &
+        run: |
+          function check_hardware_acceleration() {
+            if [[ "$HW_ACCEL_OVERRIDE" != "" ]]; then
+                hw_accel_flag="$HW_ACCEL_OVERRIDE"
+            else
+                if [[ "$OSTYPE" == "darwin"* ]]; then
+                    # macOS-specific hardware acceleration check
+                    HW_ACCEL_SUPPORT=$(sysctl -a | grep -E -c '(vmx|svm)')
+                else
+                    # generic Linux hardware acceleration check
+                    HW_ACCEL_SUPPORT=$(grep -E -c '(vmx|svm)' /proc/cpuinfo)
+                fi
+        
+                if [[ $HW_ACCEL_SUPPORT == 0 ]]; then
+                    hw_accel_flag="-accel off"
+                else
+                    hw_accel_flag="-accel on"
+                fi
+            fi
+        
+            echo "$hw_accel_flag"
+          }
+
+          hw_accel_flag=$(check_hardware_acceleration)
+
+          function launch_emulator () {
+            adb devices | grep emulator | cut -f1 | xargs -I {} adb -s "{}" emu kill
+            options="@${emulator_name} -no-window -no-snapshot -screen no-touch -noaudio -memory 2048 -no-boot-anim ${hw_accel_flag} -camera-back none"
+            if [[ "$OSTYPE" == *linux* ]]; then
+              echo "${OSTYPE}: emulator ${options} -gpu off"
+              nohup emulator $options -gpu off &
+            fi
+            if [[ "$OSTYPE" == *darwin* ]] || [[ "$OSTYPE" == *macos* ]]; then
+              echo "im here"
+              echo "${OSTYPE}: emulator ${options} -gpu swiftshader_indirect"
+              nohup emulator $options -gpu swiftshader_indirect &
+            fi
+          
+            if [ $? -ne 0 ]; then
+              echo "Error launching emulator"
+              return 1
+            fi
+          }
+
+          launch_emulator
 
       - name: Wait for emulator to launch
         run: |
